.default_tag: &default_tag
  tags:
    - backend

stages:
  - build
  - test
  - deploy
  - release

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

cache:
  paths:
    - .m2/repository/
    - target/

compile:
  stage: build
  <<: *default_tag
  script:
    - mvn -U compile

test:
  stage: test
  <<: *default_tag
  script:
    - mvn clean test -U -Pquality_check
    - cat bonsai-core/target/site/jacoco/index.html

deploy:
  stage: deploy
  <<: *default_tag
  script:
    - mvn clean deploy -U -DskipTests
  only:
    - develop

release:
  stage: release
  <<: *default_tag
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git checkout develop
    - mvn -U jgitflow:release-start jgitflow:release-finish
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop