.default: &default
  only:
    - merge_requests
    - web

.default_tag: &default_tag
  tags:
    - backend-docker-large

image: docker.phonepe.com:5000/pp-maven:3.8.4-openjdk-17

stages:
  - build
  - quality
  - deploy
  - merge
  - release

compile:
  stage: build
  <<: *default_tag
  when: manual
  allow_failure: false
  script:
    - mvn -U compile
  except:
    - master

merge_ready:
  stage: quality
  <<: *default_tag
  only:
    - merge_requests
  script:
    - mvn clean verify -U -Pquality_check -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    artifacts:
      reports:
        junit:
          - target/surefire-reports/TEST-*.xml

Stage Merge Status:
  stage: merge
  <<: *default
  <<: *default_tag
  allow_failure: false
  script:
    - git merge-base --is-ancestor $CI_COMMIT_SHA origin/stage
  only:
    - merge_requests
  when: manual
  except:
    - master
    - develop

deploy:
  stage: deploy
  <<: *default_tag
  script:
    - mvn clean deploy -U -DskipTests
  except:
    - master

release:
  stage: release
  <<: *default_tag
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git pull
    - git checkout develop
    - git pull
    - mvn -U jgitflow:release-start jgitflow:release-finish
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop