image: maven:3-jdk-8

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile -Pquality_check

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean jacoco:prepare-agent test jacoco:report
    - cat bonsai-core/target/site/jacoco/index.html

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests
  only:
    - develop

release:
  stage: release
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git checkout develop
    - mvn -U -Pdocker jgitflow:release-start jgitflow:release-finish
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop