.default_tag: &default_tag
  tags:
    - backend

stages:
  - build
  - test
  - deploy
  - release

cache:
  paths:
    - .m2/repository/
    - target/

compile:
  stage: build
  <<: *default_tag
  script:
    - mvn -U compile
  except:
    - master

test:
  stage: test
  <<: *default_tag
  script:
    - mvn clean package -U -Pquality_check
    - cat bonsai-core/target/site/jacoco/index.html
  except:
    - master

deploy:
  stage: deploy
  <<: *default_tag
  script:
    - mvn clean deploy -U -DskipTests
  except:
    - master

release:
  stage: release
  <<: *default_tag
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git pull
    - git checkout develop
    - git pull
    - mvn -U jgitflow:release-start jgitflow:release-finish
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop