package com.phonepe.platform.bonsai.core.exception;

public enum BonsaiErrorCode {
    INTERNAL_SERVER_ERROR,
    CYCLE_DETECTED,
    VARIATION_MUTUAL_EXCLUSIVITY_CONSTRAINT_ERROR,
    INVALID_INPUT,
    INVALID_STATE,
    UNSUPPORTED_OPERATION,
    KNOT_ABSENT,
    EDGE_ABSENT,
    MAPPING_ALREADY_PRESENT,
    KNOT_RESOLUTION_ERROR,
    TREE_ALREADY_EXIST,
    TREE_DOES_NOT_EXIST;
}
